# .air.toml
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main.exe ./cmd"
bin = "tmp/main.exe"
include_ext = ["go", "tpl", "templ", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "node_modules"]
delay = 10
