# .air.toml
root = "."
tmp_dir = "tmp"

[build]
cmd = "templ generate; go build -o ./tmp/main.exe ./cmd"
bin = "tmp/main.exe"
include_ext = ["go", "tpl", "templ", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "node_modules"]
exclude_regex = ["_test.go", "_templ.go"]
exclude_unchanged = false
follow_symlink = false
delay = 1000
stop_on_error = false
